#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Shotaro Yasunishi
# SPDX-License-Identifier: BSD-3-Clause
import sys

## ( 1{++}, 2{-+}, 3{+-}, 4{--}, 5{-+}, 6{+-}, 7{--], 8{-+}, 9{+-}, 10{--})

print ( float(sys.argv[1]) + float(sys.argv[2]) + float(sys.argv[3]))

print ( float(sys.argv[1]) - float(sys.argv[2]) + float(sys.argv[3]))

print ( float(sys.argv[1]) + float(sys.argv[2]) - float(sys.argv[3]))

print ( float(sys.argv[1]) - float(sys.argv[2]) - float(sys.argv[3]))

print ( float(sys.argv[2]) - float(sys.argv[1]) + float(sys.argv[3]))

print ( float(sys.argv[2]) + float(sys.argv[1]) - float(sys.argv[3]))

print ( float(sys.argv[2]) - float(sys.argv[1]) - float(sys.argv[3]))

print ( float(sys.argv[3]) - float(sys.argv[1]) + float(sys.argv[2]))

print ( float(sys.argv[3]) + float(sys.argv[1]) - float(sys.argv[2]))

print ( float(sys.argv[3]) - float(sys.argv[1]) - float(sys.argv[2]))
