#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Shotaro Yasunishi
# SPDX-License-Identifier: BSD-3-Clause
import sys

## ( 1{++}, 2{-+}, 3{+-}, 4{--})

print ( float(sys.argv[1]) + float(sys.argv[2]) + float(sys.argv[3]))

print ( float(sys.argv[1]) - float(sys.argv[2]) + float(sys.argv[3]))

print ( float(sys.argv[1]) + float(sys.argv[2]) - float(sys.argv[3]))

print ( float(sys.argv[1]) - float(sys.argv[2]) - float(sys.argv[3]))
