#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Shotaro Yasunishi
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)

*このソフトウェアパッケージは、3条項BSDライセンスの下、再頒布および使用が許可される.
* このパッケージは，aaa由来のコード（© 2022 Hoge Fuge）を利用しています．
  * このパッケージのコードは，下記のスライド（CC-BY-SA 4.0 by Ryuichi Ueda）のものを，本人の許可を得て自身の著作としたものです．
      * [ryuichiueda/my_slides robosys_2022](https://github.com/ryuichiueda/my_slides/tree/master/robosys_2022)
*©　2022　Shotaro Yasunishi

